node {
    withEnv(["ENV_CLIENT_ID=123456789"]){
        stage('init'){
            echo "${ENV_CLIENT_ID}"
            sh "printenv"
        }
    }
    stage('checkout'){
        echo "Segundo stage"
        sh "printenv"
    }
    stage('fin'){
        echo "tercer stage"
    }
}

